// src/components/music/format-selector.tsx
import { useAtom, useAtomValue } from "jotai";
import { type IdFormat, idFormat } from "./format";
import { Button } from "../ui/button";
import React from "react";

function SelectorButton(
	props: Readonly<{
		newFormat: IdFormat;
		label: React.ReactNode;
	}>,
) {
	const [format, setFormat] = useAtom(idFormat);

	return (
		<Button
			disabled={format === props.newFormat}
			onClick={() => setFormat(props.newFormat)}
		>
			{props.label}
		</Button>
	);
}

export function FormatSelector() {
	const format = useAtomValue(idFormat);
	return (
		<>
			<p>current format: {format}</p>
			<div className="flex flex-row gap-2 select-none">
				<SelectorButton label={"default"} newFormat={"DEFAULT"} />
				<SelectorButton label={"traitor town"} newFormat={"TRAITOR_TOWN"} />
			</div>
		</>
	);
}

// src/routes/music/components/format-selector.svelte
<script lang="ts">
	import { Button } from "$lib/components/ui/button/index.js";
	import { IdFormatContext, type IdFormat } from "../context";

	const format = IdFormatContext.get();
</script>

{#snippet selectorButton(newFormat: IdFormat, label: string)}
	<Button disabled={format.current === newFormat} onclick={() => (format.current = newFormat)}>
		{label}
	</Button>
{/snippet}

<p>current format: {format.current}</p>
<div class="flex flex-row gap-2 select-none">
	{@render selectorButton("DEFAULT", "default")}
	{@render selectorButton("TRAITOR_TOWN", "traitor town")}
</div>
