// src/routes/tools/index.tsx
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { seo } from "@/lib/seo";
import { TOOLS } from "@/lib/tools";
import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/tools/")({
  component: RouteComponent,
  head: () => ({
    meta: [
      ...seo({
        title: "tools - gurkan's website",
      }),
    ],
  }),
});

function RouteComponent() {
  return (
    <>
      <h1 className="text-3xl">tools</h1>
      {TOOLS.map((tool) => (
        <Card key={tool.slug}>
          <CardHeader>
            <CardTitle>{tool.title}</CardTitle>
          </CardHeader>
          <CardContent>
            <CardDescription>{tool.description}</CardDescription>
            <Button asChild>
              <Link to={`/tools/${tool.slug}`}>open</Link>
            </Button>
          </CardContent>
        </Card>
      ))}
    </>
  );
}

// src/routes/tools/+page.svelte
<script>
	import Meta from "$lib/components/meta.svelte";
	import Button from "$lib/components/ui/button/button.svelte";
	import {
		Card,
		CardContent,
		CardHeader,
		CardTitle,
		CardDescription
	} from "$lib/components/ui/card";
	import { TOOLS } from "$lib/tools";
</script>

<Meta title="tools" />

<h1 class="text-3xl">random tools</h1>

<div class="grid grid-cols-2 gap-2">
	{#each TOOLS as tool}
		<Card class="w-full max-w-xs">
			<CardHeader>
				<CardTitle>{tool.title}</CardTitle>
			</CardHeader>
			<CardContent>
				<CardDescription>{tool.description}</CardDescription>
				<Button href="/tools/{tool.slug}">open</Button>
			</CardContent>
		</Card>
	{/each}
</div>
