// src/routes/project/webhook-destroyer.tsx
import {
	createForm,
	FormError,
	reset,
	type SubmitHandler,
	zodForm,
} from "@modular-forms/solid";
import { LoaderCircle } from "lucide-solid";
import { Show } from "solid-js";
import { toast } from "solid-sonner";
import { z } from "zod";
import { Button } from "~/components/ui/button";
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "~/components/ui/card";
import {
	TextField,
	TextFieldDescription,
	TextFieldErrorMessage,
	TextFieldLabel,
	TextFieldRoot,
} from "~/components/ui/textfield";

const formSchema = z.object({
	url: z
		.string()
		.url("you need to provide a valid URL.")
		.regex(
			/^(https:\/\/(?:discord\.com|ptb\.discord\.com|canary\.discord\.com)\/api\/webhooks\/)(?:.*)$/,
			"please enter a discord webhook url",
		),
});

type FormSchema = z.infer<typeof formSchema>;

function DestroyerForm() {
	const [destroyerForm, { Form, Field }] = createForm<FormSchema>({
		validate: zodForm(formSchema),
	});

	const handleSubmit: SubmitHandler<FormSchema> = async (values) => {
		try {
			const res = await fetch(values.url, {
				method: "DELETE",
			});

			if (res.status === 204) {
				toast.success("success", {
					description: "that webhook is now deleted",
				});
				reset(destroyerForm);
				return;
			}

			toast.error("error", {
				description: "that webhook doesn't exist",
			});

			throw new FormError<FormSchema>({
				url: "that webhook doesn't exist",
			});
		} catch (err) {
			throw new FormError<FormSchema>({
				url: "that webhook doesn't exist",
			});
		}
	};

	return (
		<Form onSubmit={handleSubmit}>
			<Field name="url">
				{(field, props) => (
					<TextFieldRoot
						class="w-full max-w-xs"
						validationState={field.error ? "invalid" : "valid"}
					>
						<TextFieldLabel>webhook url</TextFieldLabel>
						<TextField
							value={field.value || ""}
							{...props}
							type="url"
							required
						/>
						<TextFieldDescription>the url to destroy</TextFieldDescription>
						<Show when={field.error}>
							<TextFieldErrorMessage>{field.error}</TextFieldErrorMessage>
						</Show>
					</TextFieldRoot>
				)}
			</Field>
			<Button
				type="submit"
				variant={"destructive"}
				disabled={destroyerForm.submitting}
			>
				<Show when={destroyerForm.submitting} fallback={<>destroy</>}>
					<LoaderCircle class="h-6 w-6 animate-spin" /> destroying
				</Show>
			</Button>
		</Form>
	);
}

export default function WebhookDestroyer() {
	return (
		<Card class="w-fit">
			<CardHeader>
				<CardTitle>webhook destroyer</CardTitle>
				<CardDescription>
					use this form to delete a discord webhook
				</CardDescription>
			</CardHeader>

			<CardContent>
				<DestroyerForm />
			</CardContent>
		</Card>
	);
}

// src/routes/tools/webhook-destroyer.tsx
import { ToolLayout } from "@/components/tool-layout";
import { useAppForm } from "@/components/ui/tanstack-form";
import { toolSeo } from "@/lib/tools";
import { useMutation } from "@tanstack/react-query";
import { createFileRoute, deepEqual } from "@tanstack/react-router";
import { z } from "zod/v4";
import { char, createRegExp, exactly } from "magic-regexp";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useStore } from "@tanstack/react-form";
import { useMemo } from "react";
import { LoaderCircle } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/tools/webhook-destroyer")({
  component: RouteComponent,
  head: () => ({
    meta: [
      ...toolSeo({
        tool: "webhook-destroyer",
      }),
    ],
  }),
});

const formSchema = z.object({
  url: z
    .url("please provide a valid URL")
    .regex(
      createRegExp(
        exactly(
          "https://",
          exactly("discord.com").or("ptb.discord.com").or("canary.discord.com"),
          "/api/webhooks/"
        )
          .grouped()
          .at.lineStart(),
        char.times.any().at.lineEnd()
      ),
      "please provide a discord webhook URL"
    ),
});

function RouteComponent() {
  const form = useAppForm({
    defaultValues: {
      url: "",
    } satisfies z.infer<typeof formSchema>,
    onSubmit: async ({ value, formApi }) => {
      const promise = mutateAsync(value.url);
      // you're probably not supposed to do this but.......
      toast.promise(promise, {
        loading: "deleting...",
        success: () => {
          formApi.reset();
          return "successfully deleted";
        },
        error: () => {
          formApi.state.fieldMeta.url.errors.push({
            message: "that webhook does not exist",
          });
          return "something went wrong";
        },
      });
    },
    validators: {
      onChange: formSchema,
    },
  });
  const { mutateAsync, isPending } = useMutation({
    mutationKey: ["webhook-destroyer", "delete"],
    mutationFn: async (webhookUrl: string) => {
      const response = await fetch(webhookUrl, {
        method: "DELETE",
      });

      if (!response.ok) {
        throw {
          status: response.status,
          message: response.statusText || "Request failed",
        };
      }

      return {
        status: response.status,
        message: response.statusText || "OK",
      };
    },
  });
  const values = useStore(form.store, (state) => state.values);

  const hasChanges = useMemo(() => {
    return !deepEqual(values, form.options.defaultValues);
  }, [values]);

  return (
    <ToolLayout tool={"webhook-destroyer"}>
      {(tool) => (
        <>
          <h1 className="text-3xl">{tool.title}</h1>
          <h2 className="text-xl">{tool.description}</h2>

          <div className="flex items-center gap-2">
            <form.AppForm>
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                  form.handleSubmit();
                }}
                method="post"
                encType={"multipart/form-data"}
              >
                <div className="space-y-4 pb-2">
                  <form.AppField
                    name="url"
                    children={(field) => (
                      <field.FormItem>
                        <field.FormLabel>webhook url</field.FormLabel>
                        <field.FormControl>
                          <Input
                            aria-invalid={!field.state.meta.isValid}
                            name={field.name}
                            value={field.state.value}
                            onChange={(e) => field.handleChange(e.target.value)}
                            onBlur={field.handleBlur}
                          />
                        </field.FormControl>
                        <field.FormMessage />
                      </field.FormItem>
                    )}
                  />
                </div>
                <form.Subscribe
                  selector={(state) => ({
                    canSubmit: state.canSubmit,
                    isSubmitting: state.isSubmitting,
                  })}
                >
                  {({ canSubmit, isSubmitting }) => (
                    <>
                      <Button
                        disabled={
                          isPending || !hasChanges || !canSubmit || isSubmitting
                        }
                        type="submit"
                        variant={"destructive"}
                      >
                        {isPending && <LoaderCircle className="animate-spin" />}{" "}
                        delete
                      </Button>
                    </>
                  )}
                </form.Subscribe>
              </form>
            </form.AppForm>
          </div>
        </>
      )}
    </ToolLayout>
  );
}
