// src/components/NavLink.tsx
import { mergeProps, type JSXElement } from "solid-js";

type NavLinkProps = {
  href: string;
  alwaysActive: boolean | undefined;
  onClick?: () => void;
  currentPathname: string;
  children: JSXElement;
};

function NavLink(props: NavLinkProps) {
  const merged = mergeProps(
    { alwaysActive: false, onClick: () => null },
    props
  );
  const isActive =
    merged.currentPathname === merged.href || merged.alwaysActive;

  return (
    <a
      onClick={() => merged.onClick()}
      href={merged.href}
      class={`flex items-center gap-2 font-semibold ${
        isActive
          ? "text-foreground"
          : "text-muted-foreground hover:text-foreground"
      } ${merged.alwaysActive ? "text-lg" : ""}`}
    >
      {merged.children}
    </a>
  );
}

export { NavLink };

// src/lib/components/nav/nav-link.svelte
<script lang="ts">
	import { page } from "$app/state";
	import type { Link } from "./link";

	type Props = {
		onclick?: () => void;
	} & Link;

	let { href, text, alwaysActive = false, onclick }: Props = $props();

	let isActive = $derived(page.url.pathname === href || alwaysActive);
</script>

<a
	{href}
	{onclick}
	class={`flex items-center gap-2 font-semibold ${isActive ? "text-foreground" : "text-muted-foreground hover:text-foreground"}`}
>
	{text}
</a>
