// src/routes/music/components/delete-music-id.svelte
<script lang="ts">
	import { Button, buttonVariants } from "$lib/components/ui/button";
	import {
		Dialog,
		DialogContent,
		DialogDescription,
		DialogFooter,
		DialogHeader,
		DialogTitle,
		DialogTrigger
	} from "$lib/components/ui/dialog/index.js";
	import LoaderCircle from "@lucide/svelte/icons/loader-circle";
	import { orpc } from "$lib/orpc";
	import type { MusicIdWithCreator } from "$lib/schemas/music";
	import { cn } from "$lib/utils";
	import { createMutation, useQueryClient } from "@tanstack/svelte-query";
	import { toast } from "svelte-sonner";

	type Props = {
		musicId: MusicIdWithCreator;
	};

	let { musicId }: Props = $props();

	let open = $state<boolean>(false);
	const queryClient = useQueryClient();
	const mutation = createMutation(() =>
		orpc.music.delete.mutationOptions({
			onSuccess: async () => {
				open = false;
				await queryClient.refetchQueries({
					queryKey: orpc.music.list.key()
				});
			}
		})
	);
</script>

<Dialog bind:open>
	<DialogTrigger class={cn(buttonVariants({ variant: "destructive" }), "w-fit")}>
		delete
	</DialogTrigger>

	<DialogContent>
		<DialogHeader>
			<DialogTitle>
				are you sure you want to delete "{musicId.name}"?
			</DialogTitle>
			<DialogDescription>
				this cannot be undone. this will permanently delete this music id, and it cannot be
				recovered.
			</DialogDescription>
		</DialogHeader>
		<DialogFooter class="grid grid-cols-2">
			<Button
				disabled={mutation.isPending}
				type="button"
				variant={"destructive"}
				onclick={() => {
					const promise = mutation.mutateAsync({
						id: musicId.id
					});
					toast.promise(promise, {
						loading: "deleting...",
						success: `successfully deleted "${musicId.name}"`,
						error: "something went wrong"
					});
				}}
			>
				{#if mutation.isPending}
					<LoaderCircle class="animate-spin" />
				{/if}
				yes
			</Button>
			<Button onclick={() => (open = false)} type="button" variant={"secondary"}>no, cancel</Button>
		</DialogFooter>
	</DialogContent>
</Dialog>

// src/components/music/delete-music-id.tsx
import { useMutation } from "@tanstack/react-query";
import { orpc } from "~/lib/orpc";
import { MusicIdWithCreator } from "~/server/db/schema/music";
import {
	Dialog,
	DialogClose,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
	DialogTrigger,
} from "~/components/ui/dialog";
import { useState } from "react";
import { Button } from "~/components/ui/button";
import { toast } from "sonner";
import { LoaderCircle } from "lucide-react";

export function DeleteMusicId(
	props: Readonly<{
		musicId: MusicIdWithCreator;
	}>,
) {
	const [open, setOpen] = useState(false);
	const { mutateAsync, isPending } = useMutation(
		orpc.music.delete.mutationOptions({
			onSuccess: async (_data, _variables, _result, { client }) => {
				await client.invalidateQueries({
					queryKey: orpc.music.list.queryKey(),
				});
			},
		}),
	);
	return (
		<Dialog open={open} onOpenChange={setOpen}>
			<DialogTrigger asChild>
				<Button variant={"destructive"} className="w-fit">
					delete
				</Button>
			</DialogTrigger>
			<DialogContent>
				<DialogHeader>
					<DialogTitle>
						are you sure you want to delete "{props.musicId.name}"?
					</DialogTitle>
					<DialogDescription>
						this cannot be undone. this will permanently delete this music id,
						and it cannot be recovered.
					</DialogDescription>
				</DialogHeader>
				<DialogFooter className="grid grid-cols-2">
					<Button
						disabled={isPending}
						type="button"
						variant={"destructive"}
						onClick={() => {
							const promise = mutateAsync({
								id: props.musicId.id,
							});
							toast.promise(promise, {
								loading: "deleting...",
								success: () => {
									setOpen(false);
									return `successfully deleted "${props.musicId.name}"`;
								},
								position: "top-center",
								error: "something went wrong",
							});
						}}
					>
						{isPending && <LoaderCircle className="animate-spin" />}
						delete
					</Button>
					<DialogClose asChild>
						<Button variant={"outline"}>cancel</Button>
					</DialogClose>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}
