// src/routes/music/components/formatted-id.svelte
<script lang="ts" module>
	import { CopyButton } from "$lib/components/ui/copy-button/index.js";
	import type { IdFormat } from "../context.js";
	export function formatId(robloxId: string, format: IdFormat = "DEFAULT") {
		switch (format) {
			case "DEFAULT": {
				return robloxId;
			}
			case "TRAITOR_TOWN": {
				return `s/${robloxId}`;
			}
			default: {
				return robloxId;
			}
		}
	}
</script>

<script lang="ts">
	import { getIdFormat } from "../context.js";
	let { robloxId }: { robloxId: string } = $props();

	const format = getIdFormat();

	const formattedId = $derived.by(() => formatId(robloxId, format.current));
</script>

<span>{formattedId}</span>
<CopyButton text={formattedId} variant={"outline"} />

// src/components/music/formatted-id.tsx
import { useAtomValue } from "jotai";
import { type IdFormat, idFormat } from "./format";
import { CopyButton } from "../ui/shadcn-io/copy-button";

function formatId(robloxId: string, format: IdFormat) {
  switch (format) {
    case "DEFAULT": {
      return robloxId;
    }
    case "TRAITOR_TOWN": {
      return `s/${robloxId}`;
    }
    default: {
      return robloxId;
    }
  }
}

export function FormattedId(
  props: Readonly<{
    robloxId: string;
  }>
) {
  const format = useAtomValue(idFormat);

  return (
    <>
      <span>{formatId(props.robloxId, format)}</span>
      <CopyButton
        variant={"outline"}
        content={formatId(props.robloxId, format)}
        delay={500}
      />
    </>
  );
}
