// src/routes/projects/+page.svelte
<script lang="ts">
	import { projects } from "$lib/projects";
	import * as Card from "$lib/components/ui/card";
	import Button from "$lib/components/ui/button/button.svelte";
</script>

<h2 class="text-3xl pb-3">projects</h2>

<div class="grid gap-2 grid-cols-2 md:grid-cols-4">
	{#each projects as project}
		<Card.Root>
			<Card.Header>
				<Card.Title>{project.title}</Card.Title>
			</Card.Header>
			<Card.Content>
				<p>{project.description}</p>
			</Card.Content>
			<Card.Footer>
				<Button href={`/project${project.slug}`}>open</Button>
			</Card.Footer>
		</Card.Root>
	{/each}
</div>

// src/routes/projects.tsx
import { For } from "solid-js";
import { ProjectCard } from "~/lib/components/project-card";
import { projects } from "~/lib/projects";

export default function Projects() {
    return (
        <>
            <h2 class="text-3xl pb-3">projects</h2>
            <div class="grid gap-2 grid-cols-2 md:grid-cols-4">
                <For each={projects}>
                    {(project) => <ProjectCard project={project} />}
                </For>
            </div>
        </>
    );
}
