// src/lib/components/field-info.svelte
<script lang="ts">
	import type { AnyFieldApi } from "@tanstack/svelte-form";

	let { field }: { field: AnyFieldApi } = $props();
</script>

{#if field.state.meta.isTouched}
	{#if !field.state.meta.isValid}
		<div class="text-destructive text-sm font-medium">
			{#each field.state.meta.errors as error}
				<div>{error.message}</div>
			{/each}
		</div>
	{/if}
{/if}

// src/components/form/field-info.tsx
import { AnyFieldApi } from "@tanstack/react-form";

export function FieldInfo({ field }: { field: AnyFieldApi }) {
  return (
    <>
      {field.state.meta.isTouched && !field.state.meta.isValid && (
        <div className="text-destructive text-sm font-medium">
          {field.state.meta.errors.map((error, index) => (
            <div key={index}>{error.message}</div>
          ))}
        </div>
      )}
    </>
  );
}
