// src/lib/components/form/text-input.svelte
<script lang="ts">
	import type { FieldElementProps } from "@formisch/svelte";
	import InputErrors from "./input-errors.svelte";
	import { Label } from "../ui/label";
	import { Input } from "../ui/input";
	import type { Snippet } from "svelte";

	type Props = {
		class?: string;
		type: "text" | "email" | "tel" | "password" | "url" | "number" | "date";
		label?: string;
		placeholder?: string;
		required?: boolean;
		input: string | number | undefined;
		errors: [string, ...string[]] | null;
		button?: Snippet;
	} & FieldElementProps;

	let {
		class: className,
		label,
		name,
		required,
		input,
		errors,
		button,
		type,
		...fieldProps
	}: Props = $props();

	let value: string | number | undefined = $state();

	$effect(() => {
		value = type === "number" && typeof input === "string" ? Number(input) : input;
	});
</script>

<div class={[className]}>
	<Label class={[!!errors && "text-destructive", "pb-2"]} for={name}>{label}</Label>
	{#if button}
		<div class="flex w-full max-w-sm items-center gap-2">
			<Input
				{...fieldProps}
				id={name}
				{type}
				{name}
				{value}
				{required}
				aria-invalid={!!errors}
				aria-errormessage={`${name}-error`}
			/>
			{@render button()}
		</div>
	{:else}
		<Input
			{...fieldProps}
			id={name}
			{name}
			{value}
			{required}
			aria-invalid={!!errors}
			aria-errormessage={`${name}-error`}
		/>
	{/if}

	<InputErrors {name} {errors} />
</div>

// src/components/form/text-input.tsx
import {
    TextField,
    TextFieldErrorMessage,
    TextFieldInput,
    TextFieldLabel,
} from "../ui/text-field";
import { createUniqueId, JSX, splitProps } from "solid-js";

type TextInputProps = {
    name: string;
    type: "text" | "email" | "tel" | "password" | "url" | "date";
    label?: string;
    placeholder?: string;
    value: string | undefined;
    error: string;
    required?: boolean;
    ref: (element: HTMLInputElement) => void;
    onInput: JSX.EventHandler<HTMLInputElement, InputEvent>;
    onChange: JSX.EventHandler<HTMLInputElement, Event>;
    onBlur: JSX.EventHandler<HTMLInputElement, FocusEvent>;
};

export function TextInput(props: TextInputProps) {
    const [, inputProps] = splitProps(props, ["value", "label", "error"]);
    const id = createUniqueId();

    return (
        <TextField validationState={props.error ? "invalid" : "valid"}>
            <TextFieldLabel for={id}>
                {props.label} {props.required && <span>*</span>}
            </TextFieldLabel>
            <TextFieldInput
                {...inputProps}
                id={id}
                value={props.value || ""}
                aria-invalid={!!props.error}
                aria-errormessage={`${props.name}-error`}
            />
            {props.error && (
                <TextFieldErrorMessage id={`${props.name}-error`}>
                    {props.error}
                </TextFieldErrorMessage>
            )}
        </TextField>
    );
}
