// src/routes/admin/+page.svelte
<script lang="ts">
	import { getUsers } from "$lib/api/admin.remote.js";
	import { getSession } from "$lib/auth.remote.js";
	import type { PageProps } from "./$types";
	import UserCard from "./components/user-card.svelte";

	let { data }: PageProps = $props();

	let users = $derived(await getUsers());
	let session = $derived(await getSession());
</script>

<h1 class="text-3xl">welcome to admin, {session?.user.name}!</h1>

<div
	class="grid w-full grid-cols-1 place-items-center gap-4 pt-4 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-5"
>
	{#each users.users as user (user.id)}
		<UserCard {user} />
	{/each}
</div>

// src/routes/admin/index.tsx
import { useQuery } from "@tanstack/react-query";
import { createFileRoute, Link, redirect } from "@tanstack/react-router";
import { getServerSession } from "~/lib/session";
import {
  Empty,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "~/components/ui/empty";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { LoaderCircleIcon } from "lucide-react";
import type { User } from "~/lib/auth";
import { Button } from "~/components/ui/button";
import { UserAvatar } from "@daveyplate/better-auth-ui";
import { listAllUsersQuery } from "~/api/admin";

export const Route = createFileRoute("/admin/")({
  beforeLoad: async () => {
    const session = await getServerSession();

    if (session?.user.role !== "admin")
      throw redirect({
        to: "/",
      });
  },
  component: RouteComponent,
});

function UserCard({
  user,
}: Readonly<{
  user: User;
}>) {
  return (
    <Card className="h-full w-full">
      <CardHeader>
        <CardTitle className="text-xl flex gap-2 items-center">
          <UserAvatar user={user} /> {user.name}
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="text-md flex items-center gap-2">
          permissions: {user.permissions.join(", ")}
        </div>
      </CardContent>
      <CardFooter className="grid grid-cols-1 gap-1">
        <p>
          role: <span> {user.role}</span>
        </p>
        <Link
          className="w-fit cursor-pointer"
          to="/admin/user/$userId"
          params={{
            userId: user.id,
          }}
        >
          <Button>manage</Button>
        </Link>
      </CardFooter>
    </Card>
  );
}

function UsersList() {
  const { data: allUsers, isPending } = useQuery(listAllUsersQuery);

  if (isPending)
    return (
      <Empty>
        <EmptyHeader>
          <EmptyMedia variant="icon">
            <LoaderCircleIcon className="animate-spin" />
          </EmptyMedia>
          <EmptyTitle>loading all users</EmptyTitle>
        </EmptyHeader>
      </Empty>
    );

  return (
    <div className="grid w-full grid-cols-1 place-items-center gap-4 pt-4 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-5">
      {allUsers?.users.map((user: User) => (
        <UserCard user={user} key={user.id} />
      ))}
    </div>
  );
}

function RouteComponent() {
  return (
    <div>
      <div className="p-2">
        <UsersList />
      </div>
    </div>
  );
}
