// src/projects/webhook-destroyer/webhook-destroyer.tsx
import { Card } from "@/components/Card";
import { Input } from "@/components/ui/Input";
import {
  createForm,
  zodForm,
  type SubmitHandler,
  FormError,
  reset,
  setResponse,
} from "@modular-forms/solid";
import { Show, createSignal } from "solid-js";
import { z } from "zod";

const formSchema = z.object({
  url: z
    .string()
    .url("you need to provide a valid URL.")
    .regex(
      /^(https:\/\/(?:discord\.com|ptb\.discord\.com|canary\.discord\.com)\/api\/webhooks\/)(?:.*)$/, // last time im ever writing a regex, this was hell
      "please enter a discord webhook url"
    ),
});

type UrlForm = z.infer<typeof formSchema>;

export function Destroyer() {
  const [urlForm, { Form, Field }] = createForm<UrlForm>({
    validate: zodForm(formSchema),
  });
  const [buttonText, setButtonText] = createSignal("destroy it");

  const handleSubmit: SubmitHandler<UrlForm> = async (values) => {
    setButtonText("wait");
    fetch(values.url, {
      method: "DELETE",
    })
      .catch(() => {
        setButtonText("destroy it");
        throw new FormError<UrlForm>(
          "something went wrong when trying to delete."
        );
      })
      .then((res) => {
        reset(urlForm);

        if (res.status === 204) {
          setResponse(urlForm, {
            status: "success",
            message: "webhook has been deleted",
          });
        } else {
          setResponse(urlForm, {
            status: "error",
            message: "that webhook does not exist",
          });
        }
      });
    setButtonText("destroy it");
  };

  return (
    <>
      <Show when={urlForm.response.status === "error"}>
        <Card type="error">{urlForm.response.message}</Card>
      </Show>
      <Show when={urlForm.response.status === "success"}>
        <Card type="success">{urlForm.response.message}</Card>
      </Show>
      <Form onSubmit={handleSubmit}>
        <Field name="url">
          {(field, props) => (
            <>
              <Input
                {...props}
                value={field.value || ""}
                type="url"
                placeholder="https://discord.com/"
                class={`w-[90%] ${field.error ? "ring-red" : ""}`}
                style={{ "font-family": "inherit" }}
                required
              />
              {field.error && <p class="text-red">{field.error}</p>}
            </>
          )}
        </Field>
        <button
          class="w-fit py-2 px-4 mt-2 text-[1.2rem]"
          style={{ "font-family": "inherit" }}
          disabled={urlForm.submitting}
        >
          {buttonText()}
        </button>
      </Form>
    </>
  );
}

// src/routes/project/webhook-destroyer/+page.svelte
<script lang="ts">
	import { superForm, defaults, setError } from "sveltekit-superforms";
	import { zod } from "sveltekit-superforms/adapters";
	import { webhookDestroyerSchema } from "./schema";
	import * as Form from "$lib/components/ui/form";
	import Input from "$lib/components/ui/input/input.svelte";
	import { toast } from "svelte-sonner";
	import { LoaderCircle } from "lucide-svelte";

	const form = superForm(defaults(zod(webhookDestroyerSchema)), {
		SPA: true,
		validators: zod(webhookDestroyerSchema),
		async onUpdate({ form }) {
			if (!form.valid) return;
			try {
				const res = await fetch(form.data.url, {
					method: "DELETE"
				});

				if (res.status === 204) {
					toast.success("success", {
						description: "that webhook is now deleted"
					});
					form.data.url = "";
					return;
				}
				toast.error("error", {
					description: "that webhook does not exist"
				});
				setError(form, "url", "that webhook does not exist");
				return;
			} catch (err) {
				setError(form, "url", "something went wrong");
			}
		},
		resetForm: false
	});

	const { form: formData, enhance, submitting } = form;
</script>

<form method="POST" use:enhance>
	<Form.Field {form} name="url">
		<Form.Control let:attrs>
			<Form.Label>url</Form.Label>
			<Input
				{...attrs}
				bind:value={$formData.url}
				placeholder="https://discord.com/api/webhooks/[webhook id]"
			/>
		</Form.Control>
		<Form.FieldErrors />
		<Form.Description>the webhook url to destroy</Form.Description>
	</Form.Field>

	<Form.Button disabled={$submitting} variant="destructive">
		{#if $submitting}
			<LoaderCircle class="mr-2 h-4- w-4 animate-spin" />
			destroying...
		{:else}
			destroy
		{/if}
	</Form.Button>
</form>
