// src/components/music/music-card.tsx
import { MusicIdWithCreator } from "@/lib/schemas/music";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export function MusicCard({ musicId }: { musicId: MusicIdWithCreator }) {
  return (
    <Card className="h-full w-full">
      <CardHeader>
        <CardTitle className="text-xl">{musicId.name}</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="flex items-center text-xl">
          <span className="pr-2">{musicId.robloxId}</span>
        </div>

        {musicId.tags && musicId.tags.length > 0 && (
          <div className="grid grid-cols-2 gap-2 mt-2">
            {musicId.tags.map((tag) => (
              <Badge key={tag} variant="outline">
                {tag}
              </Badge>
            ))}
          </div>
        )}
      </CardContent>
      <CardFooter className="grid grid-cols-1 gap-1">
        <p>
          created by <span>{musicId.creator.name}</span>
        </p>
      </CardFooter>
    </Card>
  );
}

// src/lib/components/music/music-card.tsx
import { Button } from "../ui/button";
import {
    Card,
    CardContent,
    CardFooter,
    CardHeader,
    CardTitle,
} from "../ui/card";
import { useAuth } from "@solid-mediakit/auth/client";
import { Show } from "solid-js";
import { deleteMusicId, getMusicIds, type MusicId } from "~/lib/music";

export function MusicCard(props: { musicId: MusicId }) {
    const auth = useAuth();
    const musicIdsUtils = getMusicIds.useUtils();
    const { mutate } = deleteMusicId(() => ({
        async onSettled() {
            await musicIdsUtils.invalidate();
        },
    }));

    return (
        <Card class="w-full h-full">
            <CardHeader>
                <CardTitle class="text-xl">{props.musicId.name}</CardTitle>
            </CardHeader>
            <CardContent class="flex items-center text-xl">
                <span>{props.musicId.robloxId}</span>
            </CardContent>
            <CardFooter class="grid gap-1 grid-cols-1">
                <p>created by {props.musicId.creator.name}</p>
                <Show when={auth.session()}>
                    {(session) => (
                        <>
                            <Show
                                when={
                                    session().user.id ===
                                        props.musicId.createdById ||
                                    session().user.permissions.includes(
                                        "MANAGE_MUSIC_IDS"
                                    )
                                }
                            >
                                <Button
                                    onClick={() =>
                                        mutate({
                                            id: props.musicId.id,
                                        })
                                    }
                                    class="w-fit"
                                    variant={"destructive"}
                                >
                                    delete
                                </Button>
                            </Show>
                        </>
                    )}
                </Show>
            </CardFooter>
        </Card>
    );
}
