// src/lib/components/header.svelte
<script lang="ts">
	import ModeToggle from "./mode-toggle.svelte";
	import NavLink from "./nav-link.svelte";
</script>

<nav class="flex w-full items-center gap-2 p-2">
	<NavLink activeClass="underline underline-offset-2 decoration-lime-500" href="/">home</NavLink>
	<NavLink activeClass="underline underline-offset-2 decoration-lime-500" href="/music">
		music id list
	</NavLink>

	<div class="ml-auto flex gap-2">
		<ModeToggle />
	</div>
</nav>

// src/components/header.tsx
import { Link } from "@tanstack/react-router";
import { ModeToggle } from "./mode-toggle";
import { AuthStatus } from "./auth-status";

export default function Header() {
  return (
    <header className="border-b-2 p-2 flex gap-2 justify-between">
      <nav className="items-center flex flex-row w-full">
        <div className="px-2 font-bold">
          <Link to="/">home</Link>
        </div>
        <div className="px-2 font-bold">
          <Link to="/music">music id list</Link>
        </div>

        <div className="ml-auto flex flex-row gap-2 items-center">
          <AuthStatus />
          <ModeToggle />
        </div>
      </nav>
    </header>
  );
}
