// src/routes/music/+page.svelte
<script lang="ts">
	import type { PageServerData } from "./$types";
	import AddMusicIDForm from "./add-music-id-form.svelte";
	import * as Card from "$lib/components/ui/card";
	import AudioCard from "./audio-card.svelte";
	import { createInfiniteQuery } from "@tanstack/svelte-query";
	import { api } from "$lib/api";
	import { browser } from "$app/environment";
	import { onDestroy, onMount } from "svelte";
	import type { GetMusicIdsResponse } from "$lib/music-id/type";

	export let data: PageServerData;

	const query = createInfiniteQuery({
		queryKey: ["music_ids"],
		initialPageParam: 1,
		queryFn: ({ pageParam }) => api().getMusicIds(pageParam),
		getNextPageParam: (lastPage: GetMusicIdsResponse) => {
			if (lastPage.next) {
				return +lastPage.next;
			}

			return undefined;
		}
	});

	const handleScroll = () => {
		const { scrollTop, clientHeight, scrollHeight } = document.documentElement;
		if (scrollTop + clientHeight >= scrollHeight - 20) {
			$query.fetchNextPage();
		}
	};

	$: {
		if (browser) {
			if (!$query.hasNextPage) {
				window.removeEventListener("scroll", handleScroll);
			}
		}
	}

	onMount(() => {
		if (browser) {
			window.addEventListener("scroll", handleScroll);
		}
	});

	onDestroy(() => {
		if (browser) {
			window.removeEventListener("scroll", handleScroll);
		}
	});
</script>

<h2 class="text-3xl">roblox music ID list</h2>
<p>hello! welcome to our roblox music ID list!</p>

{#if data.userIsAdmin}
	<Card.Root class="w-fit">
		<Card.Header>
			<Card.Title class="text-xl">Add a new ID</Card.Title>
		</Card.Header>
		<Card.Content>
			<AddMusicIDForm data={data.form} />
		</Card.Content>
	</Card.Root>
{/if}
{#if $query.status === "pending"}
	<span>loading</span>
{:else if $query.status === "error"}
	<span>error: {$query.error.message}</span>
{:else}
	<div
		class="pt-4 grid grid-cols-1 sm:grid-cols-2 w-full place-items-center md:grid-cols-3 xl:grid-cols-5 gap-4"
	>
		{#each $query.data.pages as page}
			{#each page.data as id}
				<AudioCard id={id.id} user={data.user} userIsAdmin={data.userIsAdmin} />
			{/each}
		{/each}
	</div>
{/if}

<button
	on:click={() => $query.fetchNextPage()}
	disabled={!$query.hasNextPage || $query.isFetchingNextPage}
>
	{#if $query.hasNextPage}
		load more
	{:else if $query.isFetching}
		loading...
	{:else}nothing more to load{/if}
</button>

// src/routes/music/index.tsx
import { useInfiniteQuery, type UseInfiniteQueryResult } from "@tanstack/solid-query";
import { FormatProvider } from "./_lib/format";
import { orpc } from "~/lib/orpc";
import { For, Show } from "solid-js";
import { ClientOnly } from "solid-use/client-only";
import { FormatSelector } from "./_lib/format-selector";
import { Button } from "~/components/ui/button";
import LoaderCircle from "lucide-solid/icons/loader-circle";
import { MusicCard } from "./_lib/music-card";
import { QueryBoundary } from "~/components/query-boundary";

function LoadMoreButton(props: { query: UseInfiniteQueryResult<unknown, Error> }) {
	return (
		<>
			{/* this is to prevent hydration mismatches since query.hasNextPage is false initially */}
			<ClientOnly fallback={<Button disabled>load more</Button>}>
				<Show when={props.query.hasNextPage}>
					<Button
						disabled={props.query.isFetchingNextPage || !props.query.hasNextPage}
						onClick={() => {
							if (props.query.hasNextPage) {
								props.query.fetchNextPage();
								return;
							}
						}}
					>
						load more
					</Button>
				</Show>
			</ClientOnly>
		</>
	);
}

export default function MusicPage() {
	const query = useInfiniteQuery(() =>
		orpc.music.getMusicIds.infiniteOptions({
			input: (pageParam: string | null) => ({
				cursor: pageParam,
				limit: 10,
				verifiedOnly: true
			}),
			getNextPageParam: (lastPage) => lastPage.nextCursor ?? undefined,
			initialPageParam: null
		})
	);

	return (
		<FormatProvider initial="DEFAULT">
			<h1 class="text-3xl">music id list</h1>

			<FormatSelector />

			<QueryBoundary
				loadingFallback={<LoaderCircle size={48} class="animate-spin" />}
				query={query}
			>
				{(data) => (
					<div class="px-2">
						<div class="pt-4 grid grid-cols-1 sm:grid-cols-2 w-full place-items-center md:grid-cols-3 xl:grid-cols-5 gap-4">
							<For each={data.pages}>
								{(page) => (
									<For each={page.data}>{(musicId) => <MusicCard musicId={musicId} />}</For>
								)}
							</For>
						</div>

						<LoadMoreButton query={query} />
					</div>
				)}
			</QueryBoundary>
		</FormatProvider>
	);
}
