// src/components/navbar.tsx
import { UserButton } from "@daveyplate/better-auth-ui";
import { Link } from "@tanstack/react-router";
import { Menu } from "lucide-react";
import { useState, type ReactNode } from "react";
import { MobileNavLink } from "~/components/mobile-nav-link";
import { Button } from "~/components/ui/button";
import { Sheet, SheetContent, SheetTrigger } from "~/components/ui/sheet";
import { ModeToggle } from "./mode-toggle";

type HeaderProps = {
  children: ReactNode;
  sheetPosition?: "left" | "right" | "top" | "bottom";
};

export function Header({
  children,
  sheetPosition = "left",
}: Readonly<HeaderProps>) {
  const [isOpen, setIsOpen] = useState(false);

  const navLinks = Array.isArray(children) ? children : [children];

  return (
    <>
      {/* Desktop Navbar */}
      <nav className="hidden md:block fixed top-4 left-1/2 -translate-x-1/2 z-50 w-[90%] max-w-5xl">
        <div className="bg-white dark:bg-black/95 backdrop-blur-sm rounded-full px-6 py-3 border border-gray-200 dark:border-white/10 shadow-lg">
          <div className="flex items-center justify-between">
            <Link to="/" className="flex items-center gap-2">
              <span className="text-black dark:text-white font-bold text-lg tracking-wide">
                gurkan's website
              </span>
            </Link>

            <div className="flex items-center gap-8">{children}</div>

            <div className="flex items-center gap-2">
              <ModeToggle />
              <UserButton size={"icon"} />
            </div>
          </div>
        </div>
      </nav>

      <nav className="md:hidden fixed top-4 left-4 right-4 z-50">
        <div className="bg-white dark:bg-black/95 backdrop-blur-sm rounded-full px-4 py-3 border border-gray-200 dark:border-white/10 shadow-lg">
          <div className="flex items-center justify-between">
            <Sheet open={isOpen} onOpenChange={setIsOpen}>
              <SheetTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon"
                  className="rounded-full bg-gray-100 hover:bg-gray-200 dark:bg-white/10 dark:hover:bg-white/20 text-black dark:text-white h-9 w-9"
                >
                  <Menu className="h-5 w-5" />
                </Button>
              </SheetTrigger>
              <SheetContent
                side={sheetPosition}
                className="bg-white dark:bg-black/98 backdrop-blur-md border-gray-200 dark:border-white/10 w-[300px] p-0"
              >
                <div className="flex flex-col h-full">
                  <div className="flex items-center justify-between px-6 py-6 border-b border-gray-200 dark:border-white/10">
                    <Link
                      to="/"
                      className="flex items-center gap-2"
                      onClick={() => setIsOpen(false)}
                    >
                      <span className="text-black dark:text-white font-bold text-base tracking-wide">
                        gurkan's website
                      </span>
                    </Link>
                  </div>

                  <div className="flex flex-col py-6 gap-1">
                    {navLinks.map((child, index) => {
                      if (
                        child &&
                        typeof child === "object" &&
                        "props" in child
                      ) {
                        const { label, to } = child.props;
                        return (
                          <MobileNavLink
                            key={`${to}-${
                              // biome-ignore lint/suspicious/noArrayIndexKey: its fine
                              index
                            }`}
                            label={label}
                            to={to}
                            onClick={() => setIsOpen(false)}
                          />
                        );
                      }
                      return null;
                    })}
                  </div>
                </div>
              </SheetContent>
            </Sheet>

            <Link to="/" className="flex items-center gap-2">
              <span className="text-black dark:text-white font-bold text-base tracking-wide">
                gurkan's website
              </span>
            </Link>

            <div className="flex flex-gap items-center gap-2">
              <ModeToggle />
              <UserButton size={"icon"} />
            </div>
          </div>
        </div>
      </nav>
    </>
  );
}

// src/lib/components/navbar.svelte
<script lang="ts">
	import { page } from "$app/state";
	import { authClient } from "$lib/auth";
	import { Sheet, SheetContent, SheetTrigger } from "$lib/components/ui/sheet/index.js";
	import ModeToggle from "./mode-toggle.svelte";
	import { buttonVariants } from "./ui/button";
	import { Menu } from "@lucide/svelte";

	type NavLinkProps = {
		label: string;
		to: string;
	};

	type NavbarProps = {
		links: NavLinkProps[];
	};

	let { links }: NavbarProps = $props();

	let sheetOpen = $state<boolean>(false);

	const session = authClient.useSession();
</script>

{#snippet navLink(props: NavLinkProps)}
	{@const active = page.url.pathname === props.to}
	<a
		href={props.to}
		class={[
			active
				? "font-medium text-primary"
				: "text-gray-700 hover:text-black dark:text-white/90 dark:hover:text-white"
		]}
		>{props.label}
	</a>
{/snippet}

{#snippet sheetNavLink(props: NavLinkProps)}
	{@const active = page.url.pathname === props.to}
	<a
		href={props.to}
		onclick={() => {
			sheetOpen = false;
		}}
		class={[
			"px-6 py-3 text-base font-medium transition-colors hover:bg-gray-100 dark:hover:bg-white/5",
			active
				? "font-medium text-primary"
				: "text-gray-700 hover:text-black dark:text-white/90 dark:hover:text-white"
		]}
	>
		{props.label}
	</a>
{/snippet}

<!-- desktop navbar -->
<nav class="fixed top-4 left-1/2 z-50 hidden w-[90%] max-w-5xl -translate-x-1/2 md:block">
	<div
		class="rounded-full border border-gray-200 bg-white px-6 py-3 shadow-lg backdrop-blur-sm dark:border-white/10 dark:bg-black/95"
	>
		<div class="flex items-center justify-between">
			<a href="/" class="flex items-center gap-2">
				<span class="text-lg font-bold tracking-wide text-black dark:text-white">
					gurkan's website
				</span>
			</a>

			<div class="flex items-center gap-8">
				{#each links as link}
					{@render navLink(link)}
				{/each}
			</div>

			<div class="flex items-center gap-2">
				<ModeToggle />
				<!-- <ModeToggle />
				<UserButton size={"icon"} /> -->
			</div>
		</div>
	</div>
</nav>

<nav class="fixed top-4 right-4 left-4 z-50 md:hidden">
	<div
		class="rounded-full border border-gray-200 bg-white px-4 py-3 shadow-lg backdrop-blur-sm dark:border-white/10 dark:bg-black/95"
	>
		<div class="flex items-center justify-between">
			<Sheet bind:open={sheetOpen}>
				<SheetTrigger
					class={buttonVariants({
						variant: "ghost",
						size: "icon",
						class:
							"h-9 w-9 rounded-full bg-gray-100 text-black hover:bg-gray-200 dark:bg-white/10 dark:text-white dark:hover:bg-white/20"
					})}
				>
					<Menu class="h-5 w-5" />
				</SheetTrigger>
				<SheetContent
					side={"left"}
					class="w-75 border-gray-200 bg-white p-0 backdrop-blur-md dark:border-white/10 dark:bg-black/98"
				>
					<div class="flex h-full flex-col">
						<div
							class="flex items-center justify-between border-b border-gray-200 px-6 py-6 dark:border-white/10"
						>
							<a href="/" class="flex items-center gap-2">
								<span class="text-base font-bold tracking-wide text-black dark:text-white">
									gurkan's website
								</span>
							</a>
						</div>

						<div class="flex flex-col gap-1 py-6">
							{#each links as link}
								{@render sheetNavLink(link)}
							{/each}
						</div>
					</div>
				</SheetContent>
			</Sheet>

			<a href="/" class="flex items-center gap-2">
				<span class="text-base font-bold tracking-wide text-black dark:text-white">
					gurkan's website
				</span>
			</a>

			<div class="flex-gap flex items-center gap-2">
				<ModeToggle />
				<!-- <ModeToggle />
				<UserButton size={"icon"} /> -->
			</div>
		</div>
	</div>
</nav>
