// src/lib/components/user-menu.svelte
<script lang="ts">
	import { authClient } from "$lib/auth";
	import {
		DropdownMenu,
		DropdownMenuContent,
		DropdownMenuLabel,
		DropdownMenuSeparator,
		DropdownMenuTrigger,
		DropdownMenuGroup,
		DropdownMenuItem
	} from "$lib/components/ui/dropdown-menu/index.js";
	import { Skeleton } from "$lib/components/ui/skeleton/index.js";
	import { CircleUserRound, LogOut, UserIcon } from "@lucide/svelte";
	import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";
	import { buttonVariants } from "./ui/button";
	import { useSession } from "$lib/session.svelte";

	const session = useSession();
</script>

{#if session.current}
	<DropdownMenu>
		<DropdownMenuTrigger>
			<Avatar class="size-8 rounded-full">
				<AvatarImage src={session.current.user.image}></AvatarImage>
				<AvatarFallback>
					<Skeleton class="size-8 rounded-full" />
				</AvatarFallback>
			</Avatar>
		</DropdownMenuTrigger>
		<DropdownMenuContent class="min-w-56 rounded-lg">
			<DropdownMenuLabel class="p-0 font-normal">
				<div class="flex items-center gap-2 px-1 py-1.5 text-start text-sm">
					<Avatar class="size-8 rounded-full">
						<AvatarImage src={session.current.user.image} alt={session.current.user.name} />
						<AvatarFallback class="rounded-lg">
							<Skeleton class="size-8 rounded-full" />
						</AvatarFallback>
					</Avatar>
					<span class="truncate font-bold">{session.current.user.name}</span>
				</div>
			</DropdownMenuLabel>
			<DropdownMenuSeparator />
			<DropdownMenuGroup>
				<DropdownMenuItem onclick={async () => await authClient.signOut()}>
					<LogOut /> log out
				</DropdownMenuItem>
			</DropdownMenuGroup>
		</DropdownMenuContent>
	</DropdownMenu>
{:else}
	<DropdownMenu>
		<DropdownMenuTrigger
			class={buttonVariants({
				size: "icon",
				variant: "secondary",
				class: "size-8 rounded-full text-black dark:text-white"
			})}
		>
			<UserIcon />
		</DropdownMenuTrigger>
		<DropdownMenuContent class="min-w-56 rounded-lg">
			<DropdownMenuLabel class="p-0 font-normal">
				<div class="flex items-center gap-2 px-1 py-1.5 text-start text-sm">
					<UserIcon />
					<div class="grid flex-1 text-start text-sm leading-tight">
						<span class="truncate font-bold">welcome!</span>
						<span class="truncate text-xs opacity-70"> please sign in </span>
					</div>
				</div>
			</DropdownMenuLabel>
			<DropdownMenuSeparator />
			<DropdownMenuGroup>
				<DropdownMenuItem
					onclick={async () =>
						await authClient.signIn.social({
							provider: "discord"
						})}
				>
					<LogOut /> log in
				</DropdownMenuItem>
			</DropdownMenuGroup>
		</DropdownMenuContent>
	</DropdownMenu>
{/if}

// src/lib/components/user-menu.tsx
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuGroup,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from "#lib/components/ui/dropdown-menu.js";
import { Skeleton } from "#lib/components/ui/skeleton.js";
import {
    Avatar,
    AvatarFallback,
    AvatarImage,
} from "#lib/components/ui/avatar.js";
import { buttonVariants } from "#lib/components/ui/button.js";
import { authClient } from "#lib/auth.js";
import {
    IconLogout,
    IconBrandDiscord,
    IconUser,
    IconSettings,
} from "@tabler/icons-react";

export function UserMenu() {
    const { data: session, isPending } = authClient.useSession();

    const handleDiscordSignIn = async () => {
        await authClient.signIn.social({
            provider: "discord",
            callbackURL: "/",
        });
    };

    if (isPending) {
        return <Skeleton className="size-8 rounded-full" />;
    }

    const username = session?.user?.username;

    return (
        <DropdownMenu>
            <DropdownMenuTrigger
                className={buttonVariants({
                    size: "icon",
                    variant: "secondary",
                    className: "size-8 rounded-full text-black dark:text-white",
                })}
            >
                {session ? (
                    <Avatar className="size-8 rounded-full">
                        <AvatarImage
                            src={session.user.image ?? undefined}
                            alt={session.user.name}
                        />
                        <AvatarFallback className="rounded-full">
                            <Skeleton className="size-8 rounded-full" />
                        </AvatarFallback>
                    </Avatar>
                ) : (
                    <IconUser size={18} />
                )}
            </DropdownMenuTrigger>

            <DropdownMenuContent
                className="min-w-56 rounded-lg"
                align="end"
                sideOffset={8}
            >
                {session ? (
                    <>
                        <DropdownMenuGroup>
                            <DropdownMenuLabel className="p-0 font-normal">
                                <div className="flex items-center gap-2.5 px-2 py-1.5 text-start text-sm">
                                    <Avatar className="size-8 rounded-full shrink-0">
                                        <AvatarImage
                                            src={
                                                session.user.image ?? undefined
                                            }
                                            alt={session.user.name}
                                        />
                                        <AvatarFallback className="rounded-full">
                                            <Skeleton className="size-8 rounded-full" />
                                        </AvatarFallback>
                                    </Avatar>
                                    <div className="grid flex-1 text-start text-sm leading-tight">
                                        <span className="truncate font-bold">
                                            {session.user.name}
                                        </span>
                                        <span className="truncate text-xs text-muted-foreground font-normal">
                                            @{username}
                                        </span>
                                    </div>
                                </div>
                            </DropdownMenuLabel>
                        </DropdownMenuGroup>

                        <DropdownMenuSeparator />

                        <DropdownMenuGroup>
                            <DropdownMenuItem
                                render={<a href="/user" />}
                                className="flex items-center gap-2"
                            >
                                <IconSettings
                                    size={18}
                                    className="text-muted-foreground shrink-0"
                                />
                                <span>user settings</span>
                            </DropdownMenuItem>

                            <DropdownMenuItem
                                onClick={() => authClient.signOut()}
                                className="flex items-center gap-2"
                            >
                                <IconLogout
                                    size={18}
                                    className="text-muted-foreground shrink-0"
                                />
                                <span>log out</span>
                            </DropdownMenuItem>
                        </DropdownMenuGroup>
                    </>
                ) : (
                    <>
                        <DropdownMenuGroup>
                            <DropdownMenuLabel className="p-0 font-normal">
                                <div className="flex items-center gap-2.5 px-2 py-1.5 text-start text-sm">
                                    <IconUser
                                        size={18}
                                        className="text-muted-foreground shrink-0"
                                    />
                                    <div className="grid flex-1 text-start text-sm leading-tight">
                                        <span className="truncate font-bold">
                                            welcome!
                                        </span>
                                        <span className="truncate text-xs opacity-70">
                                            please sign in
                                        </span>
                                    </div>
                                </div>
                            </DropdownMenuLabel>
                        </DropdownMenuGroup>

                        <DropdownMenuSeparator />

                        <DropdownMenuGroup>
                            <DropdownMenuItem
                                onClick={handleDiscordSignIn}
                                className="flex items-center gap-2"
                            >
                                <IconBrandDiscord
                                    size={18}
                                    className="text-muted-foreground shrink-0"
                                />
                                <span>sign in with discord</span>
                            </DropdownMenuItem>
                        </DropdownMenuGroup>
                    </>
                )}
            </DropdownMenuContent>
        </DropdownMenu>
    );
}
