// src/routes/login.tsx
import { createFileRoute } from "@tanstack/react-router";
import { zodValidator } from "@tanstack/zod-adapter";
import { SquareUserRound } from "lucide-react";
import * as z from "zod/v4";
import { Button } from "~/components/ui/button";
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "~/components/ui/empty";
import { authClient } from "~/lib/auth";

const loginSearchSchema = z.object({
  redirectTo: z.optional(z.string()).default("/"),
});

export const Route = createFileRoute("/login")({
  component: RouteComponent,
  validateSearch: zodValidator(loginSearchSchema),
});

function RouteComponent() {
  const searchParams = Route.useSearch();
  return (
    <Empty className="h-full bg-linear-to-b from-muted/50 from-30% to-background">
      <EmptyHeader>
        <EmptyMedia variant="icon">
          <SquareUserRound />
        </EmptyMedia>
        <EmptyTitle>please sign in</EmptyTitle>
        <EmptyDescription>
          Please sign in to access "{searchParams.redirectTo}"
        </EmptyDescription>
      </EmptyHeader>
      <EmptyContent>
        <div className="flex gap-2">
          <Button
            onClick={() =>
              authClient.signIn.social({
                provider: "discord",
                callbackURL: searchParams.redirectTo,
              })
            }
          >
            sign in
          </Button>
        </div>
      </EmptyContent>
    </Empty>
  );
}

// src/routes/login/+page.svelte
<script lang="ts">
	import * as Empty from "$lib/components/ui/empty/index.js";
	import { page } from "$app/state";
	import { signIn } from "$lib/auth.remote.js";
	import { Button } from "$lib/components/ui/button";
	import SquareUserRound from "@lucide/svelte/icons/square-user-round";

	const redirectTo = $derived(page.url.searchParams.get("redirectTo") ?? "/");
</script>

<Empty.Root class="h-full bg-linear-to-b from-muted/50 from-30% to-background">
	<Empty.Header>
		<Empty.Media variant="icon">
			<SquareUserRound />
		</Empty.Media>
		<Empty.Title>Please sign in</Empty.Title>
		<Empty.Description>
			Please sign in to access "{redirectTo}"
		</Empty.Description>
	</Empty.Header>
	<Empty.Content>
		<div class="flex gap-2">
			<form {...signIn.for("login_page")}>
				<input {...signIn.for("login_page").fields.provider.as("hidden", "discord")} />
				<input {...signIn.for("login_page").fields.redirectTo.as("hidden", redirectTo)} />
				<Button {...signIn.for("login_page").buttonProps}>log in</Button>
			</form>
		</div>
	</Empty.Content>
</Empty.Root>
