// src/lib/components/ui/alert/alert.svelte
<script lang="ts" module>
	import { type VariantProps, tv } from "tailwind-variants";

	export const alertVariants = tv({
		base: "grid gap-0.5 rounded-lg border px-2.5 py-2 text-left text-sm has-data-[slot=alert-action]:relative has-data-[slot=alert-action]:pr-18 has-[>svg]:grid-cols-[auto_1fr] has-[>svg]:gap-x-2 *:[svg]:row-span-2 *:[svg]:translate-y-0.5 *:[svg]:text-current *:[svg:not([class*='size-'])]:size-4 group/alert relative w-full",
		variants: {
			variant: {
				default: "bg-card text-card-foreground",
				destructive:
					"bg-card text-destructive *:data-[slot=alert-description]:text-destructive/90 *:[svg]:text-current"
			}
		},
		defaultVariants: {
			variant: "default"
		}
	});

	export type AlertVariant = VariantProps<typeof alertVariants>["variant"];
</script>

<script lang="ts">
	import { type WithElementRef, cn } from "#lib/utils.js";

	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		variant = "default",
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		variant?: AlertVariant;
	} = $props();
</script>

<div
	bind:this={ref}
	data-slot="alert"
	role="alert"
	class={cn(alertVariants({ variant }), className)}
	{...restProps}
>
	{@render children?.()}
</div>

// src/components/ui/alert.tsx
import type { Component, ComponentProps } from "solid-js";
import { splitProps } from "solid-js";

import { Alert as AlertPrimitive } from "@kobalte/core";
import type { VariantProps } from "class-variance-authority";
import { cva } from "class-variance-authority";

import { cn } from "~/lib/utils";

const alertVariants = cva(
	"[&>svg]:text-foreground relative w-full rounded-lg border p-4 [&>svg+div]:translate-y-[-3px] [&>svg]:absolute [&>svg]:left-4 [&>svg]:top-4 [&>svg~*]:pl-7",
	{
		variants: {
			variant: {
				default: "bg-background text-foreground",
				destructive: "border-destructive/50 text-destructive dark:border-destructive [&>svg]:text-destructive",
			},
		},
		defaultVariants: {
			variant: "default",
		},
	},
);

interface AlertProps extends AlertPrimitive.AlertRootProps, VariantProps<typeof alertVariants> {}

const Alert: Component<AlertProps> = (props) => {
	const [, rest] = splitProps(props, ["class", "variant"]);
	return <AlertPrimitive.Root class={cn(alertVariants({ variant: props.variant }), props.class)} {...rest} />;
};

const AlertTitle: Component<ComponentProps<"h5">> = (props) => {
	const [, rest] = splitProps(props, ["class"]);
	return <h5 class={cn("mb-1 font-medium leading-none tracking-tight", props.class)} {...rest} />;
};

const AlertDescription: Component<ComponentProps<"div">> = (props) => {
	const [, rest] = splitProps(props, ["class"]);
	return <div class={cn("text-sm [&_p]:leading-relaxed", props.class)} {...rest} />;
};

export { Alert, AlertTitle, AlertDescription };
